export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const CREATE_LEAGUE_SUCCESS = "CREATE_LEAGUE_SUCCESS";
export const CREATE_LEAGUE_FAIL = "CREATE_LEAGUE_FAIL";
export const JOIN_LEAGUE_SUCCESS = "JOIN_LEAGUE_FAIL";
export const JOIN_LEAGUE_FAIL = 'JOIN_LEAGUE_FAIL';
export const CREATE_LEAGUE_PENDING = 'CREATE_LEAGUE_PENDING';
export const JOIN_LEAGUE_PENDING = 'JOIN_LEAGUE_PENDING';
export const LEAGUES_LOADING = "LEAGUES_LOADING";
export const LEAGUE_LOAD_SUCCESS = "LEAGUE_LOAD_SUCCESS";
export const LEAGUE_LOAD_FAIL = "LEAGUE_LOAD_FAIL";
export const FETCHING_LEAGUE = "FETCHING_LEAGUE";
export const FETCH_LEAGUE_SUCCESS = "FETCH_LEAGUE_SUCCESS";

export const MAKING_PICK = "MAKING_PICK";
export const PICK_SUCCESS = "PICK_SUCCESS";
export const PICK_FAIL = "PICK_FAIL";

export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";

export const REFRESH_FAIL = "REFRESH_FAIL";
export const REFRESH_SUCCESS = "REFRESH_SUCCESS";

